cwlVersion: v1.1
class: Workflow
label: '04 FragPipe: TMT Integrator and QC'
doc: |-
  This workflow step executes TMT-Integrator using the report tables generated by Philosopher. The program applies a series of statistical filters, and high-quality thresholds to filter the data. Summary report tables are created containing peptides, proteins, genes, and phosphosites (only for phospho-enriched data sets).
$namespaces:
  sbg: https://sevenbridges.com

requirements:
- class: InlineJavascriptRequirement
- class: StepInputExpressionRequirement

inputs:
- id: psm_file
  type: File[]
  sbg:fileTypes: TSV
  sbg:x: -348.1875
  sbg:y: -238.8984375
- id: database
  type: File
  sbg:fileTypes: FAS
  sbg:x: -373.1875
  sbg:y: -3.898444652557373

outputs:
- id: all_report_files
  type: File[]?
  outputSource:
  - tmt_integrator_1/all_report_files
  sbg:x: 58.26561737060547
  sbg:y: -267.1984558105469
- id: tmt_qc_report
  label: TMT QC Report
  type: File?
  outputSource:
  - tmt_integrator_qc/tmt_qc_report
  sbg:x: 207.99998474121094
  sbg:y: -156.19845581054688

steps:
- id: tmt_integrator_1
  label: tmt_integrator
  in:
  - id: psm_file
    source:
    - psm_file
  - id: database
    source: database
  run: 04_FragPipe_TMT_Integrator_and_QC.cwl.steps/tmt_integrator_1.cwl
  out:
  - id: all_report_files
  - id: abundance_by_gene_report
  sbg:x: -94
  sbg:y: -111
- id: tmt_integrator_qc
  label: TMT-Integrator QC
  in:
  - id: tmt_gene_report
    source: tmt_integrator_1/abundance_by_gene_report
  run: 04_FragPipe_TMT_Integrator_and_QC.cwl.steps/tmt_integrator_qc.cwl
  out:
  - id: tmt_qc_report
  sbg:x: 49
  sbg:y: 12

hints:
- class: sbg:AWSInstanceType
  value: r5.xlarge;ebs-gp2;200
sbg:appVersion:
- v1.1
sbg:content_hash: ad2b4dc2b9b2f42a051d47618d44e30148695b46f6f687ea3637301f303eacb5c
sbg:contributors:
- david.roberson
sbg:createdBy: david.roberson
sbg:createdOn: 1618420231
sbg:id: david.roberson/pdc-workshop/tmt-integrator-wf/4
sbg:image_url: |-
  https://cgc.sbgenomics.com/ns/brood/images/david.roberson/pdc-workshop/tmt-integrator-wf/4.png
sbg:latestRevision: 4
sbg:modifiedBy: david.roberson
sbg:modifiedOn: 1618601164
sbg:original_source: |-
  https://cgc-api.sbgenomics.com/v2/apps/david.roberson/pdc-workshop/tmt-integrator-wf/4/raw/
sbg:project: david.roberson/pdc-workshop
sbg:projectName: PDC Workshop and Public Project Dev
sbg:publisher: sbg
sbg:revision: 4
sbg:revisionNotes: ''
sbg:revisionsInfo:
- sbg:modifiedBy: david.roberson
  sbg:modifiedOn: 1618420231
  sbg:revision: 0
  sbg:revisionNotes: Copy of david.roberson/pdc-webinar-devl-2/tmt-integrator-wf/6
- sbg:modifiedBy: david.roberson
  sbg:modifiedOn: 1618421556
  sbg:revision: 1
  sbg:revisionNotes: ''
- sbg:modifiedBy: david.roberson
  sbg:modifiedOn: 1618426165
  sbg:revision: 2
  sbg:revisionNotes: ''
- sbg:modifiedBy: david.roberson
  sbg:modifiedOn: 1618502375
  sbg:revision: 3
  sbg:revisionNotes: ''
- sbg:modifiedBy: david.roberson
  sbg:modifiedOn: 1618601164
  sbg:revision: 4
  sbg:revisionNotes: ''
sbg:sbgMaintained: false
sbg:toolkit: FragPipe
sbg:toolkitVersion: v15.0
sbg:validationErrors: []
